# Generated by Django 4.0.5 on 2022-11-08 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopeazy', '0004_rename_shopeazy_user_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productlist', models.CharField(max_length=255)),
                ('promocode', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('productid', models.IntegerField(primary_key=True, serialize=False)),
                ('pname', models.CharField(max_length=255)),
                ('price', models.FloatField()),
                ('category', models.CharField(max_length=255)),
                ('specifications', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderdate', models.DateTimeField(auto_now_add=True)),
                ('orderstatus', models.CharField(max_length=255)),
                ('finalprice', models.FloatField()),
                ('productid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopeazy.product')),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopeazy.user')),
            ],
        ),
    ]
