# Generated by Django 4.0.5 on 2022-11-18 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopeazy', '0005_cart_product_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.CharField(default='', max_length=255),
        ),
    ]
