# Generated by Django 4.1.2 on 2022-12-02 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopeazy', '0006_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rating',
            field=models.IntegerField(default=3),
        ),
    ]
