# Generated by Django 4.1.2 on 2022-12-03 22:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shopeazy', '0009_alter_product_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderdate', models.DateTimeField(auto_now_add=True)),
                ('orderstatus', models.CharField(max_length=255)),
                ('finalprice', models.IntegerField()),
                ('userid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopeazy.user')),
            ],
        ),
        migrations.CreateModel(
            name='CartOrderItems',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=255)),
                ('item', models.CharField(max_length=255)),
                ('image', models.CharField(max_length=255)),
                ('qty', models.IntegerField()),
                ('price', models.IntegerField()),
                ('total', models.IntegerField()),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shopeazy.cartorder')),
            ],
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
