# Generated by Django 4.1.2 on 2022-12-04 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopeazy', '0010_cartorder_cartorderitems_delete_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartorder',
            name='orderstatus',
        ),
        migrations.AddField(
            model_name='cartorder',
            name='paidstatus',
            field=models.BooleanField(default=False),
        ),
    ]
