# Generated by Django 4.1.2 on 2022-12-04 00:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopeazy', '0011_remove_cartorder_orderstatus_cartorder_paidstatus'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartorder',
            old_name='userid',
            new_name='user',
        ),
    ]
