# Generated by Django 4.0.5 on 2022-10-31 22:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopeazy', '0003_rename_user_shopeazy_user'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Shopeazy_user',
            new_name='User',
        ),
    ]
